services:
  mongo:
    image: mongo:${MONGO_IMAGE:-4}
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-guidetap}
    volumes:
      - ${MONGO_DATA_PATH:-./mongo-data}:/data/db
    logging:
      driver: none
