spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://guidetap.us.auth0.com/.well-known/jwks.json
          issuer-uri: https://guidetap.us.auth0.com/
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:guidetap}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASS:secret}
      authentication-database: admin

auth0:
  client-id: ${AUTH0_CLIENT_ID:}
  client-secret: ${AUTH0_CLIENT_SECRET:}
  audience: https://guidetap.us.auth0.com/api/v2/

login:
  client:
    web-redirect-url: http://localhost:3000/login/callback

