spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: DNo4kzMeIbciiuT5rW1clQKAfXuMQHMD
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://guidetap.us.auth0.com/

logging:
  level:
    org:
      springframework:
        web: DEBUG
